### ISSUE TITLE
TYPO3 Exception after update to TYPO3 7.6.2 using composer

### ISSUE THREAD

**Issue by rabe69** [fabarea/vidi#113]
After updating a TYPO3 6.2 installation to TYPO3 7.6.2 using composer I get this TYPO3 Exception if I try to open the media (or other moduls using vidi) backend module:
```#1289386765: Could not analyse class: "Fab\Vidi\Controller\ContentController" maybe not loaded or no autoloader?```

It seem that Migrations/Code/ClassAliasMap.php is not working.

If I add extends classes to all files in Classes/Controller/Backend to Classes/Controller, the modules (media, vidi) are working again:
```
<?php
namespace Fab\Vidi\Controller;
class ContentController extends Backend\ContentController {
}
```

**Comment by mischka** [comment]
I get this exception to, but the ClassAliasMap.php is OK.
So I think the problem is in the composer.json, because the "typo3/class-alias-loader" is missing in the extra-section.

https://github.com/TYPO3/class-alias-loader#configuration-in-composerjson

https://github.com/fabarea/vidi/blob/master/composer.json#L21-L25

to
```
	"extra": {
		"typo3/class-alias-loader": {
			"autoload-case-sensitivity": false,
			"class-alias-maps": [
				"Migrations/Code/ClassAliasMap.php"
			]
		}
	},
```
