### ISSUE TITLE
Which version is really compatible with Typo3 10?

### ISSUE THREAD

**Issue by abvdveen** [fabarea/vidi#209]
In ext_emconf.php of version 5.0.2 a dependency on 'typo3' => '10.5.0-10.5.99' is claimed. However, this version is NOT compatible with Typo3 10, as it uses use-statements in ext_tables.php, which cause a fatal error in var/cache/code/core.
See [https://stackoverflow.com/questions/60300477/use-use-in-ext-localconf-php-in-typo3-fatal-error-cannot-use-as-bec](url)

So I guess there is no version which is actually compatible and has the issues fixed that show up when you use 'Scan extension files' in the Typo3 upgrade section?

**Comment by klodeckl** [comment]
5.0.0 seems to work with TYPO3 10.

**Comment by klodeckl** [comment]
5.0.1 (on non composer install).

**Comment by klodeckl** [comment]
@fabarea No, version 4 does not run with TYPO3 10:
Argument 1 passed to TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule() must be of the type array, null given, called in /var/cg/vhosts/dev-riegg/typo3conf/ext/vidi/Configuration/TCA/Overrides/sys_domain.php on line 12

If I comment the line the next error appears:
Class 'Fab\Vidi\Module\ModuleLoader' not found
in /var/www/typo3/typo3_src-10.4.31/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 3480

So there is currently no version working with TYPO3 10 :(

**Comment by fabarea** [comment]
@klodeckl Oh. I messed up the semantic version!

For TYPO3 v10, this should be v. 5.0.1 - https://github.com/fabarea/vidi/tree/5.0.1

Actually, as of 5.0.2 it should have been 6.0.0 as we are targeting TYPO3 v11. For some time, it used to worked on both TYPO3 v10 + v11 that's because I didn't make the "big" step (6.0.0). But I had to drop support for v10 at one point which would mean we should have v 6 for ext:vidi now.

Sorry, I hope it will help nevertheless.

**Comment by klodeckl** [comment]
@fabarea I already use 5.0.1. But it seems that constraints set in User TSConfig do not work in that version. E.g. I have set a pid constraint but the editor can see all records.

**Comment by fabarea** [comment]
@klodeckl 5.0.1 is the only TYPO3 v10 compatible version. I can confirm it was running in our instances.

> But it seems that constraints set in User TSConfig do not work in that version. E.g. I have set a pid constraint but the editor can see all records.

In that case, it is a bug. I most probably overlooked this feature while upgrading to v10. Due to lack of resources, I only keep the minimum viable product from one upgrade to another and slowly phase out this extension as the list module in TYPO3 is improving.

**Comment by klodeckl** [comment]
@fabarea Would you tell me the corresponding files? Maybe I could fix it.

**Comment by fnagel** [comment]
@fabarea @klodeckl I can confirm TSconfig configuration does not work in version 6.0.0

**Comment by fnagel** [comment]
@fabarea @klodeckl I've created a PR to fix this: https://github.com/fabarea/vidi/pull/213

**Comment by klodeckl** [comment]
Thank you! PR works also in 5.0.1 (I manually made the changes).

**Comment by klodeckl** [comment]
Will there be a version vor TYPO3 12?

**Comment by fabarea** [comment]
@klodeckl yes there will be. I will be starting working on that on November.
